// PROTOTYPE — generated by make_mock_data.py, wipe me
window.MOCK = {
 "records": [
  {
   "id": "doc_000",
   "file": "320193_000032019325000079_aapl-20250927.htm",
   "company": "Apple Inc.",
   "form": "10-K",
   "filed": "2025-10-31",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "technology",
   "classification": {
    "category": "technology",
    "confidence": 0.88,
    "probabilities": {
     "technology": 0.88,
     "other": 0.11,
     "communication": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.93,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.0,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.14,
     "confidence": 0.78,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 3628
  },
  {
   "id": "doc_001",
   "file": "789019_000119312526191507_msft-20260331.htm",
   "company": "MICROSOFT CORP",
   "form": "10-Q",
   "filed": "2026-04-29",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "technology",
   "classification": {
    "category": "technology",
    "confidence": 0.92,
    "probabilities": {
     "technology": 0.92,
     "energy": 0.07,
     "consumer-discretionary": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 1.0,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.03,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.0,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.6,
     "confidence": 0.82,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 21503
  },
  {
   "id": "doc_002",
   "file": "1045810_000104581026000078_nvda-20260902.htm",
   "company": "NVIDIA CORP",
   "form": "8-K",
   "filed": "2026-09-03",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "technology",
   "classification": {
    "category": "technology",
    "confidence": 0.94,
    "probabilities": {
     "technology": 0.94,
     "industrials": 0.05,
     "communication": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.95,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.65,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 6259
  },
  {
   "id": "doc_003",
   "file": "1341439_000119312526277521_orcl-20260531.htm",
   "company": "ORACLE CORP",
   "form": "10-K",
   "filed": "2026-06-22",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "technology",
   "classification": {
    "category": "technology",
    "confidence": 0.94,
    "probabilities": {
     "technology": 0.94,
     "other": 0.05,
     "consumer-staples": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.73,
     "confidence": 0.85,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 20893
  },
  {
   "id": "doc_004",
   "file": "732712_000073271226000007_vz-20251231.htm",
   "company": "VERIZON COMMUNICATIONS INC",
   "form": "10-K",
   "filed": "2026-02-17",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "communication",
   "classification": {
    "category": "communication",
    "confidence": null,
    "probabilities": null,
    "coverage": "whole document (untruncated, claude-opus-5-5)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.96,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 3.42,
     "confidence": 0.69,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "escalated",
    "reason": "sector confidence 0.57 < 0.70",
    "first": {
     "classifier": "jev-1.13.0",
     "category": "energy",
     "confidence": 0.57,
     "probabilities": {
      "energy": 0.57,
      "technology": 0.42,
      "materials": 0.01
     },
     "coverage": "head+tail (truncated)"
    }
   },
   "pages_ocr": 0,
   "tokens": 8290
  },
  {
   "id": "doc_005",
   "file": "732717_000073271726000297_t-20260630.htm",
   "company": "AT&T INC.",
   "form": "10-Q",
   "filed": "2026-07-22",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "communication",
   "classification": {
    "category": "communication",
    "confidence": 0.89,
    "probabilities": {
     "communication": 0.89,
     "utilities": 0.1,
     "health-care": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.95,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.03,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.07,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.98,
     "confidence": 0.94,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 6268
  },
  {
   "id": "doc_006",
   "file": "1166691_000162828026049274_cmcsa-20260723.htm",
   "company": "COMCAST CORP",
   "form": "8-K",
   "filed": "2026-07-23",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "communication",
   "classification": {
    "category": "communication",
    "confidence": 0.88,
    "probabilities": {
     "communication": 0.88,
     "industrials": 0.11,
     "energy": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.8,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 12680
  },
  {
   "id": "doc_007",
   "file": "71691_000007169126000011_nyt-20251231.htm",
   "company": "NEW YORK TIMES CO",
   "form": "10-K",
   "filed": "2026-02-27",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "communication",
   "classification": {
    "category": "communication",
    "confidence": 0.91,
    "probabilities": {
     "communication": 0.91,
     "real-estate": 0.08,
     "other": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.95,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.52,
     "confidence": 0.84,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 4529
  },
  {
   "id": "doc_008",
   "file": "354950_000162828026019436_hd-20260201.htm",
   "company": "HOME DEPOT, INC.",
   "form": "10-K",
   "filed": "2026-03-18",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-discretionary",
   "classification": {
    "category": "consumer-discretionary",
    "confidence": 0.96,
    "probabilities": {
     "consumer-discretionary": 0.96,
     "other": 0.03,
     "utilities": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.96,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.07,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.95,
     "confidence": 0.83,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 3139
  },
  {
   "id": "doc_009",
   "file": "320187_000032018726000193_nke-20260831.htm",
   "company": "NIKE, Inc.",
   "form": "10-Q",
   "filed": "2026-10-02",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-discretionary",
   "classification": {
    "category": "consumer-discretionary",
    "confidence": 0.91,
    "probabilities": {
     "consumer-discretionary": 0.91,
     "utilities": 0.08,
     "consumer-staples": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.03,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.96,
     "confidence": 0.74,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 18669
  },
  {
   "id": "doc_010",
   "file": "37996_000003799626000184_f-20261002.htm",
   "company": "FORD MOTOR CO",
   "form": "8-K",
   "filed": "2026-10-02",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-discretionary",
   "classification": {
    "category": "consumer-discretionary",
    "confidence": 0.92,
    "probabilities": {
     "consumer-discretionary": 0.92,
     "technology": 0.07,
     "health-care": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.95,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.75,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 14156
  },
  {
   "id": "doc_011",
   "file": "1048286_000104828626000007_mar-20251231.htm",
   "company": "MARRIOTT INTERNATIONAL INC /MD/",
   "form": "10-K",
   "filed": "2026-02-10",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-discretionary",
   "classification": {
    "category": "consumer-discretionary",
    "confidence": 0.91,
    "probabilities": {
     "consumer-discretionary": 0.91,
     "financials": 0.08,
     "energy": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.93,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.0,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.81,
     "confidence": 0.89,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 8375
  },
  {
   "id": "doc_012",
   "file": "80424_000008042426000103_pg-20260630.htm",
   "company": "PROCTER & GAMBLE Co",
   "form": "10-K",
   "filed": "2026-08-04",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-staples",
   "classification": {
    "category": "consumer-staples",
    "confidence": 0.86,
    "probabilities": {
     "consumer-staples": 0.86,
     "materials": 0.13,
     "utilities": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 3.49,
     "confidence": 0.78,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 22637
  },
  {
   "id": "doc_013",
   "file": "21344_000162828026050503_ko-20260703.htm",
   "company": "COCA COLA CO",
   "form": "10-Q",
   "filed": "2026-07-29",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-staples",
   "classification": {
    "category": "consumer-staples",
    "confidence": 0.96,
    "probabilities": {
     "consumer-staples": 0.96,
     "real-estate": 0.03,
     "utilities": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.03,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.54,
     "confidence": 0.62,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 4606
  },
  {
   "id": "doc_014",
   "file": "56873_000110465926106890_tm2625060d1_8k.htm",
   "company": "KROGER CO",
   "form": "8-K",
   "filed": "2026-09-11",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-staples",
   "classification": {
    "category": "consumer-staples",
    "confidence": 0.92,
    "probabilities": {
     "consumer-staples": 0.92,
     "consumer-discretionary": 0.07,
     "materials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.93,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 22510
  },
  {
   "id": "doc_015",
   "file": "21665_000002166526000006_cl-20251231.htm",
   "company": "COLGATE PALMOLIVE CO",
   "form": "10-K",
   "filed": "2026-02-23",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-staples",
   "classification": {
    "category": "energy",
    "confidence": 0.6,
    "probabilities": {
     "energy": 0.6,
     "consumer-staples": 0.39,
     "industrials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.39,
     "confidence": 0.77,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.6 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 17669
  },
  {
   "id": "doc_016",
   "file": "34088_000003408826000045_xom-20251231.htm",
   "company": "ExxonMobil Holdings Corp",
   "form": "10-K",
   "filed": "2026-02-18",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "energy",
   "classification": {
    "category": "energy",
    "confidence": 0.9,
    "probabilities": {
     "energy": 0.9,
     "consumer-staples": 0.09,
     "consumer-discretionary": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.4,
     "confidence": 0.78,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 9124
  },
  {
   "id": "doc_017",
   "file": "93410_000009341026000167_cvx-20260630.htm",
   "company": "CHEVRON CORP",
   "form": "10-Q",
   "filed": "2026-08-06",
   "format": "htm",
   "status": "failed",
   "attempts": 2,
   "error": "OCR worker crashed (BrokenProcessPool)",
   "truth_sector": "energy",
   "classification": null,
   "answers": null,
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 0
  },
  {
   "id": "doc_018",
   "file": "1163165_000110465926094062_tm2622739d1_8k.htm",
   "company": "CONOCOPHILLIPS",
   "form": "8-K",
   "filed": "2026-08-11",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "energy",
   "classification": {
    "category": "energy",
    "confidence": 0.87,
    "probabilities": {
     "energy": 0.87,
     "health-care": 0.12,
     "utilities": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.87,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 13202
  },
  {
   "id": "doc_019",
   "file": "87347_000119312526021017_slb-20251231.htm",
   "company": "SLB LIMITED/NV",
   "form": "10-K",
   "filed": "2026-01-23",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "energy",
   "classification": {
    "category": "energy",
    "confidence": 0.95,
    "probabilities": {
     "energy": 0.95,
     "financials": 0.04,
     "health-care": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.82,
     "confidence": 0.72,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 3349
  },
  {
   "id": "doc_020",
   "file": "19617_000162828026008131_jpm-20251231.htm",
   "company": "JPMORGAN CHASE & CO",
   "form": "10-K",
   "filed": "2026-02-13",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "financials",
   "classification": {
    "category": "financials",
    "confidence": 0.97,
    "probabilities": {
     "financials": 0.97,
     "real-estate": 0.02,
     "health-care": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.99,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.09,
     "confidence": 0.85,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 13853
  },
  {
   "id": "doc_021",
   "file": "70858_000007085826000394_bac-20260630.htm",
   "company": "BANK OF AMERICA CORP /DE/",
   "form": "10-Q",
   "filed": "2026-07-31",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "financials",
   "classification": {
    "category": "financials",
    "confidence": 0.91,
    "probabilities": {
     "financials": 0.91,
     "energy": 0.08,
     "consumer-discretionary": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.77,
     "confidence": 0.92,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 2462
  },
  {
   "id": "doc_022",
   "file": "886982_000119312526344912_d179572d8k.htm",
   "company": "GOLDMAN SACHS GROUP INC",
   "form": "8-K",
   "filed": "2026-08-11",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "financials",
   "classification": {
    "category": "financials",
    "confidence": 0.95,
    "probabilities": {
     "financials": 0.95,
     "other": 0.04,
     "consumer-discretionary": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.67,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 8249
  },
  {
   "id": "doc_023",
   "file": "80661_000008066126000086_pgr-20251231.htm",
   "company": "PROGRESSIVE CORP/OH/",
   "form": "10-K",
   "filed": "2026-03-02",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "financials",
   "classification": {
    "category": "financials",
    "confidence": 0.95,
    "probabilities": {
     "financials": 0.95,
     "consumer-discretionary": 0.04,
     "real-estate": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.03,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.5,
     "confidence": 0.95,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 3302
  },
  {
   "id": "doc_024",
   "file": "200406_000020040626000016_jnj-20251228.htm",
   "company": "JOHNSON & JOHNSON",
   "form": "10-K",
   "filed": "2026-02-11",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "health-care",
   "classification": {
    "category": "health-care",
    "confidence": 0.99,
    "probabilities": {
     "health-care": 0.99,
     "other": 0.0,
     "consumer-staples": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 1.0,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.39,
     "confidence": 0.65,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 20366
  },
  {
   "id": "doc_025",
   "file": "78003_000007800326000095_pfe-20260628.htm",
   "company": "PFIZER INC",
   "form": "10-Q",
   "filed": "2026-08-04",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "health-care",
   "classification": {
    "category": "health-care",
    "confidence": 0.86,
    "probabilities": {
     "health-care": 0.86,
     "other": 0.13,
     "consumer-discretionary": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.99,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.03,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.07,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.3,
     "confidence": 0.89,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 9315
  },
  {
   "id": "doc_026",
   "file": "1613103_000162828026062505_mdt-20260917.htm",
   "company": "Medtronic plc",
   "form": "8-K",
   "filed": "2026-09-17",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "health-care",
   "classification": {
    "category": "energy",
    "confidence": 0.52,
    "probabilities": {
     "energy": 0.52,
     "financials": 0.47,
     "other": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.93,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.86,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.52 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 17413
  },
  {
   "id": "doc_027",
   "file": "860730_000119312526044769_hca-20251231.htm",
   "company": "HCA Healthcare, Inc.",
   "form": "10-K",
   "filed": "2026-02-10",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "health-care",
   "classification": {
    "category": "health-care",
    "confidence": 0.97,
    "probabilities": {
     "health-care": 0.97,
     "technology": 0.02,
     "materials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.07,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.6,
     "confidence": 0.78,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 16822
  },
  {
   "id": "doc_028",
   "file": "18230_000001823026000008_cat-20251231.htm",
   "company": "CATERPILLAR INC",
   "form": "10-K",
   "filed": "2026-02-13",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "industrials",
   "classification": {
    "category": "industrials",
    "confidence": 0.95,
    "probabilities": {
     "industrials": 0.95,
     "consumer-staples": 0.04,
     "energy": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.93,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.58,
     "confidence": 0.84,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 19790
  },
  {
   "id": "doc_029",
   "file": "100885_000010088526000250_unp-20260630.htm",
   "company": "UNION PACIFIC CORP",
   "form": "10-Q",
   "filed": "2026-07-23",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "industrials",
   "classification": {
    "category": "industrials",
    "confidence": 0.97,
    "probabilities": {
     "industrials": 0.97,
     "consumer-discretionary": 0.02,
     "utilities": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.0,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.4,
     "confidence": 0.76,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 3313
  },
  {
   "id": "doc_030",
   "file": "12927_000162828026059427_ba-20260824.htm",
   "company": "BOEING CO",
   "form": "8-K",
   "filed": "2026-08-28",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "industrials",
   "classification": {
    "category": "industrials",
    "confidence": 0.99,
    "probabilities": {
     "industrials": 0.99,
     "real-estate": 0.0,
     "health-care": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.76,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 19874
  },
  {
   "id": "doc_031",
   "file": "1090727_000162828026008432_ups-20251231.htm",
   "company": "UNITED PARCEL SERVICE INC",
   "form": "10-K",
   "filed": "2026-02-17",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "industrials",
   "classification": {
    "category": "industrials",
    "confidence": 0.93,
    "probabilities": {
     "industrials": 0.93,
     "energy": 0.06,
     "utilities": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.08,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.9,
     "confidence": 0.93,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 17064
  },
  {
   "id": "doc_032",
   "file": "1751788_000175178826000018_dow-20251231.htm",
   "company": "DOW INC.",
   "form": "10-K",
   "filed": "2026-02-03",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "materials",
   "classification": {
    "category": "materials",
    "confidence": 0.88,
    "probabilities": {
     "materials": 0.88,
     "real-estate": 0.11,
     "health-care": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.0,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.47,
     "confidence": 0.87,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 7460
  },
  {
   "id": "doc_033",
   "file": "73309_000119312526345891_nue-20260704.htm",
   "company": "NUCOR CORP",
   "form": "10-Q",
   "filed": "2026-08-12",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "materials",
   "classification": {
    "category": "materials",
    "confidence": 0.95,
    "probabilities": {
     "materials": 0.95,
     "health-care": 0.04,
     "consumer-staples": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.38,
     "confidence": 0.63,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 18366
  },
  {
   "id": "doc_034",
   "file": "831259_000083125926000043_fcx-20261002.htm",
   "company": "FREEPORT-MCMORAN INC",
   "form": "8-K",
   "filed": "2026-10-02",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "materials",
   "classification": {
    "category": "materials",
    "confidence": 0.95,
    "probabilities": {
     "materials": 0.95,
     "energy": 0.04,
     "consumer-staples": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.96,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.72,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 5421
  },
  {
   "id": "doc_035",
   "file": "51434_000005143426000055_ip-20251231.htm",
   "company": "INTERNATIONAL PAPER CO /NEW/",
   "form": "10-K",
   "filed": "2026-02-27",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "materials",
   "classification": {
    "category": "materials",
    "confidence": 0.86,
    "probabilities": {
     "materials": 0.86,
     "technology": 0.13,
     "real-estate": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.03,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.0,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.06,
     "confidence": 0.78,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 4506
  },
  {
   "id": "doc_036",
   "file": "1045609_000119312526051453_pld-20251231.htm",
   "company": "Prologis, Inc.",
   "form": "10-K",
   "filed": "2026-02-13",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "real-estate",
   "classification": {
    "category": "real-estate",
    "confidence": 0.99,
    "probabilities": {
     "real-estate": 0.99,
     "energy": 0.0,
     "consumer-discretionary": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 3.38,
     "confidence": 0.86,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 16236
  },
  {
   "id": "doc_037",
   "file": "1063761_000110465926093360_spg-20260630x10q.htm",
   "company": "SIMON PROPERTY GROUP INC.",
   "form": "10-Q",
   "filed": "2026-08-10",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "real-estate",
   "classification": {
    "category": "real-estate",
    "confidence": 0.95,
    "probabilities": {
     "real-estate": 0.95,
     "financials": 0.04,
     "materials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.07,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.61,
     "confidence": 0.63,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 4285
  },
  {
   "id": "doc_038",
   "file": "1138118_000113811826000021_cbre-20260729.htm",
   "company": "CBRE GROUP, INC.",
   "form": "8-K",
   "filed": "2026-07-29",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "real-estate",
   "classification": {
    "category": "real-estate",
    "confidence": 0.89,
    "probabilities": {
     "real-estate": 0.89,
     "consumer-discretionary": 0.1,
     "health-care": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.9,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 4583
  },
  {
   "id": "doc_039",
   "file": "1053507_000105350726000035_amt-20251231.htm",
   "company": "AMERICAN TOWER CORP /MA/",
   "form": "10-K",
   "filed": "2026-02-24",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "real-estate",
   "classification": {
    "category": "real-estate",
    "confidence": 0.88,
    "probabilities": {
     "real-estate": 0.88,
     "communication": 0.11,
     "industrials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.03,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 3.41,
     "confidence": 0.62,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 10213
  },
  {
   "id": "doc_040",
   "file": "753308_000075330826000015_nee-20251231.htm",
   "company": "NEXTERA ENERGY INC",
   "form": "10-K",
   "filed": "2026-02-13",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "utilities",
   "classification": {
    "category": "utilities",
    "confidence": 1.0,
    "probabilities": {
     "utilities": 1.0,
     "financials": -0.01,
     "communication": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.07,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.75,
     "confidence": 0.67,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 17004
  },
  {
   "id": "doc_041",
   "file": "1326160_000132616026000040_duk-20260630.htm",
   "company": "Duke Energy CORP",
   "form": "10-Q",
   "filed": "2026-08-04",
   "format": "htm",
   "status": "failed",
   "attempts": 2,
   "error": "HTML parse error: no <body>",
   "truth_sector": "utilities",
   "classification": null,
   "answers": null,
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 0
  },
  {
   "id": "doc_042",
   "file": "92122_000009212226000063_so-20260803.htm",
   "company": "SOUTHERN CO",
   "form": "8-K",
   "filed": "2026-08-06",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "utilities",
   "classification": {
    "category": "utilities",
    "confidence": 1.0,
    "probabilities": {
     "utilities": 1.0,
     "real-estate": -0.01,
     "materials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.83,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 20288
  },
  {
   "id": "doc_043",
   "file": "4904_000000490426000013_aep-20251231.htm",
   "company": "AMERICAN ELECTRIC POWER CO INC",
   "form": "10-K",
   "filed": "2026-02-12",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "utilities",
   "classification": {
    "category": "utilities",
    "confidence": 0.92,
    "probabilities": {
     "utilities": 0.92,
     "real-estate": 0.07,
     "financials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.99,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.08,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.09,
     "confidence": 0.85,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 23239
  },
  {
   "id": "doc_044",
   "file": "2087656_000168316826006873_myx_i10k-053126.htm",
   "company": "MYX Inc.",
   "form": "10-K",
   "filed": "2026-09-02",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "technology",
   "classification": {
    "category": "technology",
    "confidence": 0.48,
    "probabilities": {
     "technology": 0.48,
     "health-care": 0.51,
     "communication": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.99,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.93,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.41,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 0.83,
     "confidence": 0.75,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.48 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 4215
  },
  {
   "id": "doc_045",
   "file": "1939937_000168316825007621_lamy_i10k-053125.htm",
   "company": "LAMY",
   "form": "10-K",
   "filed": "2025-10-17",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "industrials",
   "classification": {
    "category": "industrials",
    "confidence": 0.54,
    "probabilities": {
     "industrials": 0.54,
     "materials": 0.45,
     "utilities": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.95,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.88,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.54,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 0.44,
     "confidence": 0.76,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.54 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 7562
  },
  {
   "id": "doc_046",
   "file": "2010982_000168316826001953_palisades_i10k-123125.htm",
   "company": "Palisades Venture Inc.",
   "form": "10-K",
   "filed": "2026-03-18",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "technology",
   "classification": {
    "category": "other",
    "confidence": 0.49,
    "probabilities": {
     "other": 0.49,
     "financials": 0.5,
     "industrials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.95,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.96,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.89,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 0.75,
     "confidence": 0.94,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.49 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 12543
  },
  {
   "id": "doc_047",
   "file": "1696411_000147793225001313_crona_10k.htm",
   "company": "Crona Corp.",
   "form": "10-K",
   "filed": "2025-02-27",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "industrials",
   "classification": {
    "category": "industrials",
    "confidence": 0.47,
    "probabilities": {
     "industrials": 0.47,
     "communication": 0.52,
     "materials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.8,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.64,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 0.7,
     "confidence": 0.78,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.47 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 2562
  },
  {
   "id": "doc_048",
   "file": "1392449_000165495426003081_gplb_10k.htm",
   "company": "Green Planet Bio Engineering Co. Ltd.",
   "form": "10-K",
   "filed": "2026-03-31",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "health-care",
   "classification": {
    "category": "health-care",
    "confidence": 0.44,
    "probabilities": {
     "health-care": 0.44,
     "consumer-discretionary": 0.55,
     "energy": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.95,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.81,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.42,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 0.22,
     "confidence": 0.68,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.44 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 21588
  },
  {
   "id": "doc_049",
   "file": "1970129_000168316826006219_legend_i10k-123125.htm",
   "company": "LEGEND SPICES, INC.",
   "form": "10-K",
   "filed": "2026-08-12",
   "format": "htm",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-staples",
   "classification": {
    "category": "other",
    "confidence": 0.58,
    "probabilities": {
     "other": 0.58,
     "consumer-staples": 0.41,
     "utilities": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.94,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.81,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.56,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.18,
     "confidence": 0.85,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.58 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 23477
  },
  {
   "id": "doc_050",
   "file": "pdf/320193_000032019325000079_aapl-20250927.pdf",
   "company": "Apple Inc.",
   "form": "10-K",
   "filed": "2025-10-31",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "technology",
   "classification": {
    "category": "technology",
    "confidence": 0.98,
    "probabilities": {
     "technology": 0.98,
     "real-estate": 0.01,
     "industrials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.06,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.62,
     "confidence": 0.78,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 2926
  },
  {
   "id": "doc_051",
   "file": "pdf/789019_000119312526191507_msft-20260331.pdf",
   "company": "MICROSOFT CORP",
   "form": "10-Q",
   "filed": "2026-04-29",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "technology",
   "classification": {
    "category": "technology",
    "confidence": 0.94,
    "probabilities": {
     "technology": 0.94,
     "other": 0.05,
     "energy": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 1.0,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.0,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.77,
     "confidence": 0.73,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 17191
  },
  {
   "id": "doc_052",
   "file": "pdf/1045810_000104581026000078_nvda-20260902.pdf",
   "company": "NVIDIA CORP",
   "form": "8-K",
   "filed": "2026-09-03",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "technology",
   "classification": {
    "category": "technology",
    "confidence": 0.95,
    "probabilities": {
     "technology": 0.95,
     "other": 0.04,
     "real-estate": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "current-report",
     "confidence": 0.99,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "skipped: Section mdna missing"
    },
    "material_weakness": {
     "kind": "noul",
     "value": null,
     "coverage": "skipped: Section controls missing"
    },
    "outlook": {
     "kind": "score",
     "value": null,
     "confidence": 0.86,
     "coverage": "skipped: Section mdna missing"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 18881
  },
  {
   "id": "doc_053",
   "file": "pdf/71691_000007169126000011_nyt-20251231.pdf",
   "company": "NEW YORK TIMES CO",
   "form": "10-K",
   "filed": "2026-02-27",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "communication",
   "classification": {
    "category": "communication",
    "confidence": 0.87,
    "probabilities": {
     "communication": 0.87,
     "technology": 0.12,
     "consumer-staples": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.99,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 3.16,
     "confidence": 0.68,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 0,
   "tokens": 9124
  },
  {
   "id": "doc_054",
   "file": "pdf/1392449_000165495426003081_gplb_10k.pdf",
   "company": "Green Planet Bio Engineering Co. Ltd.",
   "form": "10-K",
   "filed": "2026-03-31",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "health-care",
   "classification": {
    "category": "health-care",
    "confidence": 0.56,
    "probabilities": {
     "health-care": 0.56,
     "real-estate": 0.43,
     "technology": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.95,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.93,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.44,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.11,
     "confidence": 0.62,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.56 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 23135
  },
  {
   "id": "doc_055",
   "file": "pdf/1970129_000168316826006219_legend_i10k-123125.pdf",
   "company": "LEGEND SPICES, INC.",
   "form": "10-K",
   "filed": "2026-08-12",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-staples",
   "classification": {
    "category": "other",
    "confidence": 0.43,
    "probabilities": {
     "other": 0.43,
     "technology": 0.56,
     "consumer-staples": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.79,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.73,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 0.89,
     "confidence": 0.65,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.43 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 0,
   "tokens": 18207
  },
  {
   "id": "doc_056",
   "file": "pdf/354950_000162828026019436_hd-20260201.scan.pdf",
   "company": "HOME DEPOT, INC.",
   "form": "10-K",
   "filed": "2026-03-18",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-discretionary",
   "classification": {
    "category": "consumer-discretionary",
    "confidence": 0.9,
    "probabilities": {
     "consumer-discretionary": 0.9,
     "other": 0.09,
     "consumer-staples": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.04,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.05,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.97,
     "confidence": 0.76,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 15,
   "tokens": 17681
  },
  {
   "id": "doc_057",
   "file": "pdf/320187_000032018726000193_nke-20260831.scan.pdf",
   "company": "NIKE, Inc.",
   "form": "10-Q",
   "filed": "2026-10-02",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-discretionary",
   "classification": {
    "category": "consumer-discretionary",
    "confidence": 1.0,
    "probabilities": {
     "consumer-discretionary": 1.0,
     "technology": -0.01,
     "financials": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.95,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.02,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 2.39,
     "confidence": 0.63,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 15,
   "tokens": 19000
  },
  {
   "id": "doc_058",
   "file": "pdf/21344_000162828026050503_ko-20260703.scan.pdf",
   "company": "COCA COLA CO",
   "form": "10-Q",
   "filed": "2026-07-29",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "consumer-staples",
   "classification": {
    "category": "consumer-staples",
    "confidence": 0.92,
    "probabilities": {
     "consumer-staples": 0.92,
     "health-care": 0.07,
     "real-estate": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "quarterly-report",
     "confidence": 0.97,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.01,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.08,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.78,
     "confidence": 0.65,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "none"
   },
   "pages_ocr": 15,
   "tokens": 19572
  },
  {
   "id": "doc_059",
   "file": "pdf/1696411_000147793225001313_crona_10k.scan.pdf",
   "company": "Crona Corp.",
   "form": "10-K",
   "filed": "2025-02-27",
   "format": "pdf",
   "status": "done",
   "attempts": 1,
   "error": null,
   "truth_sector": "industrials",
   "classification": {
    "category": "other",
    "confidence": 0.61,
    "probabilities": {
     "other": 0.61,
     "consumer-staples": 0.38,
     "utilities": 0.01
    },
    "coverage": "head+tail (truncated)"
   },
   "answers": {
    "doc_type": {
     "kind": "choice",
     "value": "annual-report",
     "confidence": 0.98,
     "coverage": "head+tail"
    },
    "going_concern": {
     "kind": "noul",
     "value": 0.92,
     "coverage": "mdna, financial_statements"
    },
    "material_weakness": {
     "kind": "noul",
     "value": 0.65,
     "coverage": "controls"
    },
    "outlook": {
     "kind": "score",
     "value": 1.09,
     "confidence": 0.68,
     "coverage": "mdna"
    }
   },
   "escalation": {
    "status": "flagged",
    "reason": "sector confidence 0.61 < escalate_below 0.70 \u2014 over escalation_max (2%), flagged only"
   },
   "pages_ocr": 15,
   "tokens": 18329
  }
 ],
 "jobs": [
  {
   "id": "job_0007",
   "name": "corpus-60 \u00b7 sector + filing risk",
   "status": "running",
   "total": 60,
   "taxonomy": "sector (12 Categories)",
   "question_sets": [
    "filing-risk v3 (sha 9f2c\u2026)"
   ],
   "profile": "fast",
   "escalate_below": 0.7,
   "escalation_max": "2%",
   "started": "10:42",
   "eta": "~4 min"
  },
  {
   "id": "job_0008",
   "name": "q3-10Q batch \u00b7 filing risk only",
   "status": "queued",
   "total": 1840,
   "taxonomy": null,
   "question_sets": [
    "filing-risk v3"
   ],
   "profile": "fast",
   "position": 1
  },
  {
   "id": "job_0009",
   "name": "non-US annual reports (PDF)",
   "status": "queued",
   "total": 212,
   "taxonomy": "sector (12 Categories)",
   "question_sets": [],
   "profile": "quality",
   "position": 2
  },
  {
   "id": "job_0006",
   "name": "articles triage \u00b7 week 40",
   "status": "done",
   "total": 84,
   "taxonomy": "reading-priority (4 Categories)",
   "question_sets": [],
   "profile": "fast"
  },
  {
   "id": "job_0005",
   "name": "8-K sweep Sept",
   "status": "cancelled",
   "total": 3100,
   "taxonomy": "doc-type (5 Categories)",
   "question_sets": [],
   "profile": "fast"
  }
 ],
 "sectors": [
  "communication",
  "consumer-discretionary",
  "consumer-staples",
  "energy",
  "financials",
  "health-care",
  "industrials",
  "materials",
  "real-estate",
  "technology",
  "utilities",
  "other"
 ]
};
